import type { Metadata } from "next";
import "../globals.css";
import { useLocale, useMessages, useTimeZone } from "next-intl";
import ClientProviders from "@/providers/ClientProviders";
import Footer from "../ui/components/common/Footer";
import Header from "../ui/components/header";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const messages = useMessages();
  const locale = useLocale();
  const timeZone = useTimeZone();
  return (
    <ClientProviders messages={messages} locale={locale} timeZone={timeZone}>
      <html lang="en">
        <body>
          <Header />
          {children}
          <Footer />
        </body>
      </html>
    </ClientProviders>
  );
}
